controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    
    gains:
      lift_joint:
        p: 2000.0
        i: 200.0
        d: 100.0
        i_clamp: 200.0
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      lift_joint:
        trajectory: 0.05
        goal: 0.02